// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfzrrgaklqjlabarekmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmenJyZ2FrbHFqbGFiYXJla21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTM2NzYsImV4cCI6MjA3MzQ4OTY3Nn0.x2E8y6eE73wEDHX1meiLAfaM_y1fO7XLzMCgKZR1eP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});